#baseurl = "https://tarumzu.github.io/"
#title = "tarumzu"
#
#theme = "hugo-coder"
#
#languagecode = "ja"
#defaultcontentlanguage = "ja"
#
#paginate = 20
#canonifyurls = true
#
#pygmentsstyle = "b2"
#pygmentscodefences = true
#pygmentscodefencesguesssyntax = true
#
#disqusShortname = "taru"
#
#[params]
#    author = "Wataru Mizukami"
#    description = "tarumzu's personal website"
#    keywords = "blog,developer,personal,Android,Rails,Docker,Vim"
#    info = "Engineer Android/Rails/Docker/Vim"
#    avatarurl = "images/avatar.jpg"
#    footercontent = "🐰💪"
#
#    dateformat = "January 2, 2006"
#
#    hideCredits = false
#    hideCopyright = false
#
#    # Git Commit in Footer, uncomment the line below to enable it.
#    #commit = "https://github.com/luizdepra/hugo-coder/tree/"
#
#    rtl = false
#
#    # Specify light/dark colorscheme
#    # Supported values:
#    # "auto" (use preference set by browser)
#    # "dark" (dark background, light foreground)
#    # "light" (light background, dark foreground) (default)
#    colorscheme = "light"
#
#    # Series see also post count
#    maxSeeAlsoItems = 5
#
#    # Custom CSS
#    custom_css = []
#
#    # Custom JS
#    custom_js = []
#
#[taxonomies]
#  category = "categories"
#  series = "series"
#  tag = "tags"
#
#[[params.social]]
#    name = "Diary"
#    icon = "fa fa-book-open fa-lg"
#    weight = 1
#    url = "https://tarumzu.hateblo.jp/"
#[[params.social]]
#    name = "Github"
#    icon = "fab fa-github"
#    weight = 2
#    url = "https://github.com/tarumzu/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter"
#    weight = 3
#    url = "https://twitter.com/tarumzu/"
#[[params.social]]
#    name = "LinkedIn"
#    icon = "fab fa-linkedin"
#    weight = 4
#    url = "https://www.linkedin.com/in/watarumizukami/"
#[[params.social]]
#    name = "SpeakerDeck"
#    icon = "fab fa-speaker-deck"
#    weight = 5
#    url = "https://speakerdeck.com/tarumzu"
#
#[languages]
#    [languages.ja]
#        languagename = "Japanese"
#
#        [languages.ja.menu]
#
#            [[languages.ja.menu.main]]
#            name = "Qiita"
#            weight = 1
#            url = "https://qiita.com/tarumzu"
#
#            [[languages.ja.menu.main]]
#            name = "Contact me"
#            weight = 9
#            url = "contact/"
#
#    [languages.pt-br]
#        languagename = "Japanese"
#
#        [languages.pt-br.menu]
#
#            [[languages.pt-br.menu.main]]
#            name = "Qiita"
#            weight = 1
#            url = "https://qiita.com/tarumzu"
#
#            [[languages.pt-br.menu.main]]
#            name = "Contact me"
#            weight = 9
#            url = "contact/"


baseurl = "http://www.example.com"
title = "johndoe"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "John Doe"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack DevOps and Magician"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@johndoe"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.pt-br]
        languagename = "Português"
        title = "João Ninguém"

        [languages.pt-br.params]
            author = "João Ninguém"
            info = "Full Stack DevOps e Mágico"
            description = "Sítio pessoal de João Ninguém"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Coloque algum texto aqui."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "contact/"
