baseurl = "https://tarumzu.github.io"
title = "tarumzu Site"

theme = "hugo-coder"

languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "taru"

[params]
    author = "Wataru Mizukami"
    description = "tarumzu's personal website"
    keywords = "blog,developer,personal,Android,Rails,Docker,Vim"
    info = "Android App Engineer/Firebase/Rails/Docker/Vim"
    avatarurl = "https://avatars2.githubusercontent.com/u/9943053?s=460"
    footercontent = ""

    dateformat = "January 2, 2006"
    since = 2019

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github"
    weight = 1
    url = "https://github.com/tarumzu/"
[[params.social]]
    name = "SpeakerDeck"
    icon = "fa-brands fa-speaker-deck"
    weight = 2
    url = "https://speakerdeck.com/tarumzu"
[[params.social]]
    name = "Qiita"
    weight = 3
    url = "https://qiita.com/tarumzu"
[[params.social]]
    name = "Twitter"
    icon = "fa-brands fa-x-twitter"
    weight = 4
    url = "https://twitter.com/tarumzu/"
[[params.social]]
    name = "Bluesky"
    weight = 5
    url = "https://bsky.app/profile/tarumzu.bsky.social"
[[params.social]]
    name = "Threads"
    icon = "fa-brands fa-threads"
    weight = 6
    url = "https://www.threads.net/@tarumzu"
[[params.social]]
    name = "Diary"
    icon = "fa fa-book-open fa-lg"
    weight = 7
    url = "https://tarumzu.hateblo.jp/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin"
    weight = 8
    url = "https://www.linkedin.com/in/watarumizukami/"

[languages]
    [languages.ja]
        languagename = "Japanese"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "Contact me"
            weight = 1
            url = "contact/"
